---
# Install i3-wm

- name: Ensure i3 is present
  apt: pkg={{item}} update_cache=true force=yes state=present
  with_items:
    - i3-wm
    - dunst
    #- i3lock
    - i3status
    - libxdg-basedir1
    - suckless-tools

#  Ubuntu Mate like to keep the i3 config file /.config/i3
- name: Ensure i3 config directory
  file: path=/home/{{remote_user}}/.config/i3 state=directory

- name: Set permissions for i3 config directory
  file: path=/home/{{remote_user}}/.config/i3 recurse='yes' owner={{remote_user}} group={{remote_user}} mode='u=rwX'

- name: Ensure i3 config
  copy: src={{item}} dest=/home/{{remote_user}}/.config/i3/ owner={{remote_user}} group={{remote_user}} mode='u=rw'
  with_fileglob:
   - i3/*


- name: Ensure bin directory
  file: path=/home/{{remote_user}}/bin state=directory

- name: Set permissions for bin directory
  file: path=/home/{{remote_user}}/bin recurse='yes' owner={{remote_user}} group={{remote_user}} mode='u=rwX'

- name: Add useful scripts at bin
  copy: src={{item}} dest=/home/{{remote_user}}/bin owner={{remote_user}} group={{remote_user}} mode='u=rwx'
  with_fileglob:
   - bin/*






